docs/getting_started/installation.md
In the installation instructions, some instructions for configuration of the postgreSQL database refer to something "above" that is actually "below" where it is located.
=> Fix incorrect location-sensitive verbiage

docs/plugins/pluggable_authentication.md
The iRODS directory no longer exists in /var/lib/irods as of 4.2+ so the location of irodsctl needs to be updated.
=> Fix irodsctl location in auth documentation

docs/system_overview/configuration.md
Default Resource Configuration now always returns SYS_RESC_DOES_NOT_EXIST.
Previously, an iput targeting a resource that does not exist would redirect the put
to the default resource if "null" was used in msiSetDefaultResc.
=> [irods/irods#4084] Update Default Resource section (master)

docs/system_overview/configuration.md
Default Resource Configuration now always returns SYS_RESC_DOES_NOT_EXIST.
Previously, an iput targeting a resource that does not exist would redirect
the put to the default resource if "null" was used in msiSetDefaultResc.
=> [irods/irods#4084] Update Default Resource section (4-2-stable)

docs/system_overview/troubleshooting.md
Adds instructions for how to use iadmin modrepl to get out of the ol'
data-object-stuck-in-lock-status issue. In the future, it may be worth
considering a mention about clients using data_object_finalize to
atomically unlock a data object.
=> [irods/irods#5421] Add iadmin modrepl troubleshooting (master)

docs/plugins/pluggable_rule_engine.md
This small change documents a new feature in iRODS server whereby INST_NAME can be used alongside other hints in the 2nd parameter of the irods rule language's remote( ) execution call.
A corresponding feature is being added to the the Python RE plugin's py_remote( ) microservice and  will be separately documented in that repo's front page README.
=> [irods/irods#6465] add INST_NAME to change remote call documentation

docs/system_overview/troubleshooting.md
In service of irods/irods#6136
Adds a section to Troubleshooting for digging out of the "`iexit` as service account" situation.
=> [irods/irods#6136] `iexit` as service account tip (main)

docs/plugins/pluggable_authentication.md, docs/system_overview/configuration.md, docs/system_overview/federation.md, docs/system_overview/glossary.md
In service of irods/irods#7274
Still working on the issue itself (tests are finding serious problems) but figured I would go ahead and put this up for eyeballs on the words.
=> [irods/irods#7274] Add authentication configuration docs

.github/workflows/build-docs.yml, Dockerfile, requirements.txt
Addresses #216 
We can't update to Ubuntu 22.04 until 4.3.1 is released. In the meantime, this seems to work both in GitHub Actions and on my local machine (docker version 24.0.6).
=> [#216] Update builder image

docs/plugins/pluggable_authentication.md
Addresses irods/irods#4904
My understanding is that we have no plans to update irodsPamAuthCheck itself. If anything, we would write a different tool for use in the future if we wanted to make any changes.
Also, happy to squash down to one if we're into it.
=> [irods/irods#4904] irodsPamAuthCheck: Add more docs (main)

docs/getting_started/download.md
There are two commits, each mostly presenting the same information, just in different ways.
Let me know which one seems better.
=> Add EOL policy to downloads page (main)

docs/plugins/composable_resources.md, docs/system_overview/data_objects.md
Addresses irods/irods#6940
In service of irods/irods#7468
In service of irods/irods#7476
Still need to implement/merge changes before all of this is true. Think of this as requirements gathering :)
=> Update Replicate and Trim documentation, add unixfilesystem voting documentation

docs/administrators/policy_cookbook.md, docs/developers/library_examples.md
Addresses #230 
Addresses #231
I did not transfer these issues to the 4.3.2 milestone in case we wanted to fix this in 4.3.1 documentation as well. Even if we don't, I wouldn't consider this a blocker for 4.3.2, so that is why I left them. Please let me know if we'd rather these issues be in the 4.3.2 milestone and I will transfer them and update the issue numbers appropriately.
Verified locally, but the problem does not manifest on locally running irods_docs sites, so it's hard to tell. I just copied how other places linked to these same pages in other places since those links work.
=> [#230,#231] Fix broken links

docs/system_overview/genquery.md, docs/system_overview/troubleshooting.md, mkdocs.yml
Addresses irods/irods#6631
I already spent the time on this so I'm putting this up here, but we don't have to use it.
The only thing the issue calls for is the error codes and a page for `iquest attrs`, so, take what seems good and we'll throw out the rest (which could be all of it)
=> Add error codes to troubleshooting and a page for GenQuery

docs/plugins/irods_rule_language.md
More words to explain why `on()` might do weird things; recommending `if()` as well.
=> [irods/irods7268] Add extra warning to advise users against using on()

docs/administrators/policy_cookbook.md
Addresses #204 
I tried to provide as much context as possible, but maybe it's a bit too much for the cookbook. Happy to rip out stuff.
=> [#204] Policy Cookbook: Add finalize database operation PEP example

docs/system_overview/troubleshooting.md
Addresses #289 
Confirmed that list renders appropriately on locally-generated docs.irods.org site.
=> [#289] Troubleshooting: Fix list rendering for TCP keepalive

docs/administrators/policy_cookbook.md
=> [irods/irods#7773] Policy Cookbook: Access info for opened replicas

docs/system_overview/configuration.md
Issue quick link: irods/irods#7392.
`irods_connection_pool_refresh_time_in_seconds` is not optional since 4.3.1, so this change removes the `(Optional)` annotation from the documentation.
=> [irods/irods#7392] Fix: Remove '(optional)' from required option (main)

docs/system_overview/configuration.md, docs/system_overview/data_objects.md, docs/system_overview/troubleshooting.md
Here's a rendering of the wording for one section.
=> [irods/irods#7949] Add note about deprecating parallel transfer over the high ports (main)

docs/getting_started/upgrading.md
In service of irods/irods#7834
=> [irods/irods#7834] Upgrading: Remove update_deprecated_database_columns.py mention (main)

docs/system_overview/configuration.md
Removes documentation on `msiSendMail`, which was removed in iRODS 5.0.
=> [irods/irods#8278] Remove documentation on `msiSendMail` (main)

docs/system_overview/troubleshooting.md
=> [8319] Add documentation for GenQuery1 log category (main)

docs/getting_started/installation.md, docs/plugins/pluggable_database.md, docs/system_overview/configuration.md
Issue quick link: irods/irods#7975
This PR attempts to update the documentation surrounding the new database schema.
A quick search for areas of interest was done by grepping `database`. Updates were then applied where considered needed.
=> [irods/irods#7975] Update documentation surrounding the database plugin (main)

docs/system_overview/troubleshooting.md, docs/system_overview/users_and_permissions.md
Issue quick link: irods/irods#7985
This PR attempts to remove all out-of-date documentation on StrictACLs. This PR also provides minor documentation informing that "StrictACL" is now always on as of iRODS 5.0.
=> [irods/irods#7985] Remove documentation on modifying StrictACLs (main)

docs/system_overview/troubleshooting.md
Linked the `irodsProt` commit to the SQL logging commit. Seemed okay since what remained after the removal of SQL docs looked out of place.
If there's a better issue to link against, let me know. Perhaps I'll open an issue for the `irodsProt` in this repo?
=> [irods/irods#8489] SQL logging / irodsProt update (main)

docs/system_overview/control_plane.md
Companion PR at https://github.com/irods/irods/pull/8645.
Here's a rendering of the changes.
=> [irods/irods#8479] Document deprecation of control plane (4-3-stable)
