docs/system_overview/configuration.md
Fixes irods/irods#3112
Found this old issue while checking something, hope this little fix is useful
=> link to levels table

docs/plugins/composable_resources.md
Description of the replication retry mechanism along with the settings used to configure it.
=> Add docs for replication retry mechanism

docs/developers/logging_library.md, docs/getting_started/running.md
Documentation for new modes:
- irods/irods#4418
- irods/irods#4472
Also made some adjustments to the new logging API developer docs.
=> Added documentation about new server modes (master)

docs/system_overview/federation.md
Open to suggestions on organizing the information.
=> Add minimal 3.x federation instructions (master)

Makefile, README.md
Corrected the MAKEIRODSVERSION value to point to 4-2-stable by default.
=> [#62] Added support for building docs for different repos (4-2-stable)

docs/plugins/pluggable_rule_engine.md
=> [irods/irods#2759] Documented <PRIORITY> delay rule hint (4-2-stable)

docs/plugins/pluggable_rule_engine.md
=> [irods/irods#2759] Documented <PRIORITY> delay rule hint (master)

docs/system_overview/troubleshooting.md
cherry-picked from changes made for #100
=> [irods/irods#5421] Add iadmin modrepl troubleshooting (4-2-stable)

docs/getting_started/installation.md
To help explain the values asked for by setup_irods.py
=> [irods/irods5757] add link to beginner training (4-2-stable)

docs/getting_started/installation.md
To help explain the values asked for by setup_irods.py
=> [irods/irods5757] add link to beginner training (master)

docs/system_overview/configuration.md
I don't know if this is necessarily true. I would expect a FQDN to work as well.
=> [#116] Add clarification to hosts_config.json (4-2-stable)

docs/system_overview/configuration.md
cherry-picked from work done for #117
=> [#116] Add clarification to hosts_config.json (master)

docs/plugins/composable_resources.md
=> [irods/irods#6089] Add comment about archive replicas and checksums (4-2-stable)

Makefile, docs/plugins/composable_resources.md
=> [irods/irods#6089] Add comment about archive replicas and checksums (main)

.github/workflows/build-docs.yml, Dockerfile, Makefile, README.md, docs/developers/logging.md, run_make.sh
@trel What is the iteration process for this?
I made changes before standing everything up and those were visible in the browser. Since then, I've made additional changes but those don't appear at all. I've tried restarting the httpd server and that didn't work.
I feel like something has been cached.
=> [#20] Update documentation for logging library (main)

docs/system_overview/troubleshooting.md
- Clarifies iadmin modrepl inputs
- Clarifies replica statuses and their meaning
- Adds an example of digging out of the hole
=> [#145] Expand locked object Troubleshooting (4-2-stable)

docs/administrators/policy_cookbook.md, docs/developers/library_examples.md, mkdocs.yml
- Introduces a new section for capturing known policy techniques to various problems
- Absorbs the https://github.com/irods/irods_library_examples
=> Policy Cookbook and Library Examples (main)

docs/plugins/composable_resources.md
=> [#180] add read/write weights of zero to passthru (4-2-stable)

docs/system_overview/troubleshooting.md
=> Updated docs for log message structure (main)

docs/plugins/dynamic_policy_enforcement_points.mdpp
=> Updated dynamic PEP explanation involving BytesBuf (4-2-stable)

docs/plugins/irods_rule_language.md, docs/plugins/pluggable_rule_engine.md
Putting this in draft until we agree on the wording.
Feel free to review whenever.
Important changes:
- Removed the rulebase image
- Removed bullet list about fallthrough behavior
- Updated example
- Enabled footnotes in mkdocs config (look for \[^1] to see an example)
- Updated irule, delay, and remote sections
=> [irods/irods#6286] Updated REPF documentation (main)

docs/plugins/irods_rule_language.md, docs/plugins/pluggable_rule_engine.md
Cherry-picked from #200.
Updated REP links to point to 4-2-stable.
I think everything else is identical to main, but I'll do one last pass to make sure everything still applies.
=> [irods/irods#6286] Updated REPF documentation (4-2-stable)

docs/system_overview/configuration.md
Addresses irods/irods#6342
Addresses irods/irods#6370
Accompanies irods/irods#6762
=> Document new configuration settings (main)

docs/system_overview/configuration.md, docs/system_overview/troubleshooting.md
Addresses irods/irods#3986
Related to https://github.com/irods/irods/pull/7215
=> [irods/irods#3986] Add docs for TCP keepalive options

docs/system_overview/configuration.md
Addresses #233
Addresses irods/irods#5701
=> [irods/irods#5701] Add parallel transfer threads section (main)

docs/developers/deprecation.md, mkdocs.yml
Addresses #124
I have not tried to render this yet. Please give suggestions - especially on the TODO part :)
=> [#124] Developer Docs: Add deprecation rules

docs/index.md
Here's a rendering of the home page for what will be 4.3.2.
=> [irods/irods#7618] Document process for reporting security vulnerabilities (main)

docs/plugins/dynamic_policy_enforcement_points.mdpp, dynamic_peps.json
I think I got all of the newer APIs. If I missed one, let me know.
=> [#7575] Update docs for dynamic PEPs (main)

docs/developers/contributing.md
Still need to render the text to see what it looks like.
=> [#252] Add section describing rules for including TODO comments (main)

docs/getting_started/installation.md
Here's a rendering of the text.
=> [irods/irods#6719] Add note about overwrite behavior of unattended installations (main)

docs/getting_started/installation.md
In service of irods/irods#7382
=> [irods/irods#7382] Fix installation instructions for Postgres 15+

docs/system_overview/genquery.md
=> [#262] GenQuery: Fix list renderings

docs/getting_started/installation.md
Addresses #267
Addresses irods/irods#7495
=> [#267,irods/irods#7495] Update for MySQL 8.4

docs/plugins/irods_rule_language.md
First shot at this. Taking comments on whether it's detailed enough or not, etc.
Seems to work ok when tested locally via docker.
=> [irods/irods7268] Clarify documentation on NREP condition behavior

docs/getting_started/installation.md
=> [irods/irods#7905] Document MariaDB compatibility situation

README.md, docs/release_notes.md, requirements.txt
for monday release
marking as draft, only to prevent accidental merging.   please review for goodness and completeness.
=> [irods/irods_7852] add release notes for 4.3.3

docs/system_overview/troubleshooting.md
=> [#291] Troubleshooting: Authentication TTL default behavior

docs/developers/schema_versions.md, mkdocs.yml
Here's a rendered version of the changes.
=> [irods/irods#7701,irods/irods#8000] Document how to manage schema versions (main)

docs/plugins/irods_rule_language.md, docs/release_notes.md, docs/system_overview/genquery.md
This is a WIP.
Please double check issue numbers and wording.
NTS: Check for duplicate issue numbers.
Leaving in draft for now. Feedback welcome.
=> [irods/irods#8203] Add release notes for 4.3.4 (main)

docs/plugins/dynamic_policy_enforcement_points.mdpp
=> [irods/irods#5952] Revert deprecation of Static Policy Enforcement Points

docs/plugins/pluggable_network.md
Addresses #307
Cherry-picked from #329
=> [#307] Pluggable Network: Update default acPreConnect value (4-3-stable)

docs/system_overview/configuration.md, docs/system_overview/tls.md
Addresses irods/irods#6706 (I think)
=> [irods/irods#6706] More TLS and server configuration docs (main)

docs/system_overview/genquery.md
=> [irods/irods#8096] GenQuery1: Document character escaping enhancement (main)

docs/plugins/pluggable_authentication.md
In service of irods/irods#8360
=> [irods/irods#8360] pam_password: Update TLS requirements wording (main)

dynamic_peps.json
=> [#355] Remove xmsg PEPs (4-3-stable)

docs/release_notes.md
~**This is a WIP.**~
The goal of the release notes is to highlight the **most important changes** to the software for users, not every change.
All issues and commits for irods/irods as of 2025-05-10 18:56:00 are listed in this PR. To view the list of issues/commits which are currently unlikely to be captured in the release notes, scroll to the bottom of the diff. You'll come across a separator with the title `ISSUES POOL`.
Some changes may be highlighted in the release summary/description depending on the level of importance and other factors.
The information was produced using a python script I wrote which filters the commits to main against the issue list for the 4.3.5 and 5.0.0 milestones. The issue list was obtained using the GitHub CLI.
```bash
gh issue list -m 5.0.0 -s all -L 200 …
```
=> [irods/irods#8451] Add release notes for iRODS 5.0.0 (main)

docs/system_overview/tls.md
=> [irods/irods#8537] TLS: Fix server configuration info (main)

docs/release_notes.md
=> [irods/irods8539] reorder

docs/system_overview/federation.md
In service of irods/irods#6826
Not sure what else to write about this but definitely open to suggestions on what we might like to see here.
=> [irods/irods#6826] Federation: Describe consumer redirection
